/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rtrk_pnrs_clockgame_Game */

#ifndef _Included_rtrk_pnrs_clockgame_Game
#define _Included_rtrk_pnrs_clockgame_Game
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rtrk_pnrs_clockgame_Game
 * Method:    incrementTime
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_rtrk_pnrs_clockgame_Game_incrementTime
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     rtrk_pnrs_clockgame_Game
 * Method:    decrementTime
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_rtrk_pnrs_clockgame_Game_decrementTime
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
